### ISSUE TITLE
Un tile d'herbe

### ISSUE THREAD

**Issue by MrBSmith** [MrBSmith/Haven#11]

**Comment by QuentinPeyrache** [comment]
![Tile Herbe 1](https://user-images.githubusercontent.com/72989233/96369054-08f4fe80-1158-11eb-87e1-bc09694ea9bc.png)

**Comment by QuentinPeyrache** [comment]
![Tile Herbe 1 Without Borders](https://user-images.githubusercontent.com/72989233/97106289-fc752680-16c0-11eb-8cab-34e6fcb1385d.png)
