### ISSUE TITLE
Un tile de terre

### ISSUE THREAD

**Issue by MrBSmith** [MrBSmith/Haven#12]

**Comment by QuentinPeyrache** [comment]
![Tile Terre 1](https://user-images.githubusercontent.com/72989233/96369119-5f623d00-1158-11eb-80c1-56d1f7c1e18b.png)

**Comment by QuentinPeyrache** [comment]
![Tile Terre 1 Without Borders](https://user-images.githubusercontent.com/72989233/97106317-17e03180-16c1-11eb-9d8f-363e973f3e8b.png)
