### ISSUE TITLE
Sprite Chêne

### ISSUE THREAD

**Issue by MrBSmith** [MrBSmith/Haven#13]

**Comment by QuentinPeyrache** [comment]
![Sprite Young Tree Oak](https://user-images.githubusercontent.com/72989233/97110680-da889d80-16da-11eb-9d72-18f46cb5738f.png)

**Comment by QuentinPeyrache** [comment]
![Sprite Adolescent Tree Oak](https://user-images.githubusercontent.com/72989233/97110683-df4d5180-16da-11eb-89f1-c35f9a7b4425.png)

**Comment by QuentinPeyrache** [comment]
![Sprite Adult Tree Oak](https://user-images.githubusercontent.com/72989233/97110685-e2e0d880-16da-11eb-95fa-ce0cfbc84272.png)
